const projects = [
    {
      id:'1',
      title: 'HQ-ReadMeGen',
      description: 'This is a command-line application that can quickly and easily create a README file for a project',
      technologies: ['Node.js', 'Inquirer', 'JavaScript'],
      imageUrl: '/Images/ReadMeGen.png',
      githubLink: 'https://github.com/lenworth425/HQ-ReadMeGen/blob/main/media/Screenshot%20(15).png?raw=true',
    },
    {
      id:'2',
      title: 'Ultimate Vehicle Builder',
      description: 'The Ultimate Vehicle Builder is an application prompts the user to create a new vehicle or select an existing vehicle.',
      technologies: ['TypeScript', 'Inquirer', 'Node.js'],
      imageUrl: '/Images/UltimateVehicleBuilder.png',
      githubLink: 'https://github.com/lenworth425/ultimate-vehicle-builder.git',
    },
    {
      id:'3',
      title: 'Employee Tracker',
      description: 'This is a command-line application that can quickly and easily create a README file for a project',
      technologies: ['Node.js', 'Inquirer', 'MySQL', 'TypeScript'],
      imageUrl: '/Images/EmployeeTracker.png',
      githubLink: 'https://github.com/lenworth425/Employee-tracker.git',
    },
    {
      id:'4',
      title: 'Weather Dashboard',
      description: 'This is a weather dashboard that will run in the browser and feature dynamically updated HTML and CSS.',
      technologies: ['HTML', 'CSS', 'JavaScript', 'OpenWeather API'],
      imageUrl: '/Images/WeatherDashboard.png',
      githubLink: 'https://github.com/lenworth425/My-Personal-Weather.git',
    },
    {
      id:'5',
      title: 'MadLibs Mashup',
      description: 'Mad Libs Mashup is a web-based game that transforms ordinary words into extraordinary stories.',
      technologies: ['HTML', 'CSS', 'JavaScript', 'Bootstrap'],
      imageUrl: '/Images/MadLibs.png',
      githubLink: 'https://github.com/Dom-Darling/Aus05_mad_lib.git',
    },
    {
      id:'6',
      title: 'Portfolio',
      description: 'This website servers as a creation of a portfolio using my new React skills. ',
      technologies: ['HTML', 'CSS', 'React','JavaScript'],
      imageUrl: '/Images/Portfolio.png',
      githubLink: 'https://github.com/lenworth425/Lenworth-Portfolio.git',
    },
  ];
  export default projects;